### ISSUE TITLE
False errors marked on things from Prelude

### ISSUE THREAD

**Issue by chris-martin** [rikvdkleij/intellij-haskell#166]
IntelliJ is always red-underlining identifiers from `Prelude` unless they're imported explicitly.

I suspect it's because my default Stack project has `NoImplicitPrelude` enabled, and IntelliJ is incorrectly inferring that it applies to all projects.

**Comment by rikvdkleij** [comment]
Can you give example project? I use Protolude for my projects so I also have NoImplicitPrelude enabled and do not notice this problem

**Comment by chris-martin** [comment]
Just any example of a project that doesn't globally enable NoImplicitPrelude? https://github.com/kim/leveldb-haskell

This seems to happen for other extensions as well. I'm editing a file now where IntelliJ seems to think that `OverloadedStrings` is enabled and causing all sorts of type ambiguity, but it isn't.

**Comment by rikvdkleij** [comment]
Okay, I see, This isssue is related to https://github.com/rikvdkleij/intellij-haskell/issues/129. Workaround is to enable only target which you are working on by commenting the others ones out.

I have to change plugin to handle each target of Cabal file on it's own. Probably I will create for each target a repl. But quite some work.

**Comment by chris-martin** [comment]
Sorry, I think I've mislead you. It's not my Stack config that's the problem, I believe, it's that's I have `:set -XNoImplicitPrelude` in my `~/.ghc/ghci.conf`.

**Comment by chris-martin** [comment]
Yes, confirmed - if I remove the lines that enable ghc extensions from `~/.ghc/ghci.conf`, then IntelliJ works properly.

**Comment by rikvdkleij** [comment]
The plugin itself does not read `~/.ghc/ghci.conf`. It's read by stack repl (ghci). To my knowledge I can not change this behavior. I have put my default language extensions in project's Cabal file.

**Comment by steshaw** [comment]
I wonder if it might be a good idea to tell `ghci` to avoid reading `~/.ghc/ghci.conf`?

There's a [`--ignore-dot-ghci` flag](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/ghci.html#ghc-flag--ignore-dot-ghci
).

I noticed that while `intellij-haskell` uses an intero invocation:

```
stack repl --with-ghc intero --verbosity warn --no-build --terminal --no-load --no-package-hiding
```

whereas vscode/haskero uses:

```
stack ghci --with-ghc intero --no-build --no-load --ghci-options=-ignore-dot-ghci -Wall
```

A google search brought up a related issue with the [intero Emacs mode](https://github.com/commercialhaskell/intero/pull/356).

**Comment by rikvdkleij** [comment]
> I wonder if it might be a good idea to tell ghci to avoid reading ~/.ghc/ghci.conf?

I think it's good idea :smile: I will change the way the repl is started in this way.

**Comment by rikvdkleij** [comment]
This should be fixed in beta7.

**Comment by chris-martin** [comment]
Yep, looks good to me.

**Comment by chris-martin** [comment]
Actually, the `OverloadedStrings` issue is still present - but it's a different issue. #180
