### ISSUE TITLE
Unnecessary auto-closing parenthesis

### ISSUE THREAD

**Issue by Unisay** [rikvdkleij/intellij-haskell#176]
Please compare auto-closing behaviour in Intellij-Haskell plugin:

Here you can see that `)` is automatically added when `(` is typed in front of `id`
Auto-closing behaviour is not desirable in this case.

![haskell](https://cloud.githubusercontent.com/assets/1009751/25266739/897c3250-2672-11e7-8a64-a25296d3f2e3.gif)

For comparison check out how Scala plugin behaves:
Here `)` is **not** automatically added when `(` is typed before `"bar"`

![scala](https://cloud.githubusercontent.com/assets/1009751/25266742/8baa6bc8-2672-11e7-8073-9b1a197a0b96.gif)

**Comment by rikvdkleij** [comment]
Should be fixed in beta8.

**Comment by Unisay** [comment]
Still doesn't work correctly in some cases (I am on beta8)

![closingparentesis](https://cloud.githubusercontent.com/assets/1009751/25564635/d618ea3a-2db7-11e7-8691-3a8804e307c4.gif)

**Comment by rikvdkleij** [comment]
Hmm, github closed this issue automatically...

**Comment by rikvdkleij** [comment]
Should be fixed in beta 9
