### ISSUE TITLE
build is triggered multiple times when editing library code

### ISSUE THREAD

**Issue by maiermic** [rikvdkleij/intellij-haskell#207]
> **Unisay**: I have a problem with plugin, and I suspect it wasn't there before. And here it is: if my project not in the state when it could be build without errors (say, stack build runs fine) then plugin says "Haskell support is not available when Stack repl is not running" and then for any change in project files it re-tries to build it and fails. And because it does it for every change (I edited 1 character) it makes it harder to bring project back to the buildable state because it slows down IDE by continuously re-building it and failing.
What I expect it to do is not to re-trigger build automatically (on change) but rather let me first fix it and then press "compile" button
:point_up: [17. August 2017 17:31](https://gitter.im/intellij-haskell/Lobby?at=5995b6bcee5c9a4c5fcebb78)

> **rikvdkleij:** So what I want to make clear, fixing library code would not trigger rebuild. Only when you navigate to test, exe or benchmark code.
If you are experience also rebuilds in library code, it is a bug and I need some example project to reproduce this issue
:point_up: [18. August 2017 11:12](https://gitter.im/intellij-haskell/Lobby?at=5996af98210ac269209716d7)

I experienced the same issue in my [project](https://github.com/maiermic/haskell-sdl2-jump-and-run/tree/552688d769f0d348ddc353f292aad1d66c1a2b34). A moment after I edit one of my library files in the `src` directory a rebuild is triggered. If I wait a few seconds and edit again another rebuild is triggered even though the previous build might still be running. This can be done multiple times. Once I had 12 processes running at the same time. I don't have this issue when I edit my exe [main](https://github.com/maiermic/haskell-sdl2-jump-and-run/blob/552688d769f0d348ddc353f292aad1d66c1a2b34/app/Main.hs) file.

---

Linux
Stack 1.5.0
Intellij-Haskell 1.0.0-beta10
Intellij IDEA 2017.2.2

**Comment by rikvdkleij** [comment]
Thanks for reporting and for project to reproduce this issue.

Btw, can you try beta11?

**Comment by maiermic** [comment]
Same issue in beta11.

**Comment by rikvdkleij** [comment]
Is it solved by reimporting your project?

**Comment by maiermic** [comment]
I did another import without deleting any project files (like the _.idea_ directory) beforehand. The issue still exists, but I realized that the issue only appears if I have the main file open in split mode. The main file has to be the active tab of a split pane, but the focus (cursor) can be in the library file (other split pane).

**Comment by maiermic** [comment]
I usually use a vertically split. The main file on the left side and the library files on the right.

```
|----------||-----------------|
|Main|     ||Lib1|Lib2|       |
|----------||-----------------|
|          ||                 |
|          ||                 |
|          ||                 |
|----------||-----------------|
```

**Comment by BobNobrain** [comment]
I have this issue with the only Main.hs tab opened. I start typing and then it starts to compile and moves cursor inside editor like crazy, making further editing completely impossible

**Comment by rikvdkleij** [comment]
@BobNobrain can you give more information about your issue? Which project and what does the Haskell Event Log contains?

**Comment by rikvdkleij** [comment]
@maiermic Your issue is (probably) fixed in master. I have created a snapshot release, so you can give it a try.
https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0.beta12-snapshot

**Comment by maiermic** [comment]
@rikvdkleij This issue is still present in beta12-snapshot.

**Comment by rikvdkleij** [comment]
@maiermic Do you know for sure it's a build and not something else?

I could reproduce your issue with split windows. So I could fix the issue and the multiple builds did not happen anymore without reason. But later on I noticed that finding type information in the not selected editor was still happening. I fixed that later on. If you like I can upload a not snapshot release. Do you want to try it again?

**Comment by rikvdkleij** [comment]
@maiermic If you want to try it again, I have uploaded new snapshot.

**Comment by maiermic** [comment]
@rikvdkleij When I tried it before, I somehow managed to trigger the start of multiple processes. However, it didn't happen on the first tries. I'm not sure if they were build processes. I tried to reproduce the issue again to check it, but I didn't trigger any unexpected processes this time. I would say the main issue is fixed and you can do a regular release/upload. If I run into the problem again, I will reopen the issue again and add more details. Thanks for your efforts :+1:

**Comment by rikvdkleij** [comment]
@maiermic Thanks for testing!
