### ISSUE TITLE
"Stack repl is not started because of problem" / "Stack Repl could not be started" / Intero-Service-Port

### ISSUE THREAD

**Issue by aryairani** [rikvdkleij/intellij-haskell#277]
The plugin is in a loop, saying `Stack repl could not be started within 5 seconds` every 5 seconds.

The `stack` commands at the command-line seem to work fine: 
```
$ /usr/local/bin/stack exec -- hlint --json /Users/arya/unison/parser-typechecker/tests/Unison/Test/TermParser.hs
[]
$ /usr/local/bin/stack build --fast
$ /usr/local/bin/stack repl unison-parser-typechecker:exe:tests --with-ghc intero --no-load --no-build --ghci-options=-ignore-dot-ghci --silent
Intero-Service-Port: 50180
Prelude>
```
Is there something unexpected about the intero output?  I noticed that `Intero-Service-Port` appears in the plugin logs below, which makes me think `stack` is "starting" fine, but not recognized as such.

```
5/21/18
6:53 PM	[project-stack-repl-unison-parser-typechecker:exe:tests] Intero-Service-Port: 50153

6:53 PM	Restart daemon code analyzer for file: TermParser.hs

6:53 PM	/usr/local/bin/stack exec -- hlint --json /Users/arya/unison/parser-typechecker/tests/Unison/Test/TermParser.hs:  [] 
				

6:53 PM	Starting to execute `stack build --fast`

6:53 PM	[project-stack-repl-unison-parser-typechecker:exe:tests] Stack repl will be started with command: /usr/local/bin/stack repl unison-parser-typechecker:exe:tests --with-ghc intero --no-load --no-build --ghci-options=-ignore-dot-ghci --silent

6:53 PM	[project-stack-repl-unison-parser-typechecker:exe:tests] Intero-Service-Port: 50153
				Intero-Service-Port: 50154

6:53 PM	Restart daemon code analyzer for file: TermParser.hs

6:53 PM	/usr/local/bin/stack exec -- hlint --json /Users/arya/unison/parser-typechecker/tests/Unison/Test/TermParser.hs:  [] 
				

6:53 PM	Starting to execute `stack build --fast`

6:53 PM	[project-stack-repl-unison-parser-typechecker:exe:tests] Stack repl will be started with command: /usr/local/bin/stack repl unison-parser-typechecker:exe:tests --with-ghc intero --no-load --no-build --ghci-options=-ignore-dot-ghci --silent
...
```

Thanks!

**Comment by rikvdkleij** [comment]
It looks like the REPL can not be started because a dependency could not be build without errors. Probably the library of your package.

**Comment by aryairani** [comment]
The log shows 3 stack commands:

```
10:35 AM	Initializing Haskell project

10:35 AM	Starting to execute `stack build --fast --test --bench --no-run-tests --no-run-benchmarks --only-dependencies`

10:35 AM	Starting to execute `stack build --fast`

10:35 AM	Starting to execute `stack intero`

10:35 AM	/usr/local/bin/stack build intero:  /usr/local/bin/stack build intero
				

10:35 AM	/usr/local/bin/stack build intero:  WARNING: Ignoring out of range dependency (allow-newer enabled): ghc-8.4.2. intero requires: >=7.8 && <=8.4.1
				

10:35 AM	Building `intero` is finished successfully

10:35 AM	[global-stack-repl] Stack repl will be started with command: /usr/local/bin/stack repl --with-ghc intero --no-load --no-build --ghci-options=-ignore-dot-ghci --silent --no-package-hiding --test
```

They all run and terminate successfully, except for the last one which appears opens a REPL and remains running. e.g.

```
/usr/local/bin/stack repl --with-ghc intero --no-load --no-build --ghci-options=-ignore-dot-ghci --silent --no-package-hiding --test
Intero-Service-Port: 61712
Prelude>
```

**Comment by aryairani** [comment]
Thanks for the offer, that would be great.  
`git clone git@github.com:unisonweb/unison.git --branch topic/typechecker`

I'm seeing a never-ending series of "Stack repl could not be started within 5 seconds", "No result from stack repl within 5 seconds",  "Haskell support is not available when Stack repl is not running." although it appears to my untrained eye that each of the individual stack commands the plugin is running *are* successful.

**Comment by aryairani** [comment]
<img width="810" alt="screen shot 2018-05-25 at 1 09 53 pm" src="https://user-images.githubusercontent.com/538571/40557075-f2d43772-601c-11e8-8b51-6f7f91c4669c.png">

**Comment by rikvdkleij** [comment]
I can reproduce this issue but I do not know yet how to solve it. It only occurs with the REPL without target and for this unison project. The problem is that the custom "intellij-haskell" prompt is not set when the REPL is started from within IntelliJ.

**Comment by rikvdkleij** [comment]
I tried to understand the issue but no, I can not find the cause. It seems to be a specific issue for this Unison project (it looks like it is doing something with the JVM runtime).

**Comment by aryairani** [comment]
Doing something with the JVM runtime?  Don't let the folder names be a distraction.  I created a new branch for you with some irrelevant files removed.  You can `git checkout temp/intellij-haskell` or
`git clone git@github.com:unisonweb/unison.git --branch temp/intellij-haskell` if you are willing to take another look at it.  Thanks!

**Comment by rikvdkleij** [comment]
> Doing something with the JVM runtime?

Yes, it is just a guess but it's really a weird issue 😄 

Also when I startup the REPL from within IntelliJ in another way (without referring to the ghci script) and want to set the prompt, the REPL does not respond. 
Also Intero is not loaded when it fails.

Note, that Intero is not yet supported for GHC 8.4.2  But I already changed the compiler to 8.2.2 and it did not help.

Which OS are you using?

I will take another look.....

**Comment by aryairani** [comment]
Sorry for any misunderstanding, the project doesn’t use or interact with the JVM runtime.  I am using macOS.  Thanks for your help!

**Comment by rikvdkleij** [comment]
Okay, I understand the problem.
This project has targets:
```
easytest:lib
easytest:exe:runtests
easytest:test:tests
parsec-layout:lib
unison-parser-typechecker:lib
unison-parser-typechecker:exe:tests
```

All the targets have by default the default verbosity except the last target (`unison-parser-typechecker:exe:tests`).

When the Stack REPL is started without target, Stack decides to take the verbosity of `unison-parser-typechecker:exe:tests`. This has as consequence that even the prompt is not displayed in the REPL so the plugin does not know when the output of one command is finished.

I will fix the plugin by forcing the verbosity to `-v1` and you can solve it now by changing the verbosity of `unison-parser-typechecker:exe:tests` to `-v1` in the `parser-typechecker/unison-parser-typechecker.cabal` file.

**Comment by aryairani** [comment]
Thanks for taking another look.  I tried implementing your suggested workaround here https://github.com/unisonweb/unison/commit/ba12789e5cb2dfe517b71970ae103adbb231d943 but I don't see any difference yet in the plugin behavior yet.  Is this what you meant?

**Comment by aryairani** [comment]
Explicitly setting them to `-v1` didn't seem to change things either; maybe I misunderstood?

**Comment by rikvdkleij** [comment]
That's a pity. I got it working on master. I hope to release a new (prerelease) version soon.

**Comment by aryairani** [comment]
Would you share what you did to get my project working on master?  Maybe maybe a diff or PR against the branch I created [here](https://github.com/unisonweb/unison/tree/temp/intellij-haskell) for debugging this issue?  Thanks in advance.

**Comment by rikvdkleij** [comment]
I wrote down what I did to get it working (without my fix) but that was still with the plugin master build. So the reason that it stills not works for you is because you are using other version of the plugin. I hope to release new version of the plugin soon.

**Comment by rikvdkleij** [comment]
@aryairani I have released new version of plugin https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta14
It's also uploaded it to Alpha channel of Jetbrains plugin repo but that can take some time before it's published

**Comment by aryairani** [comment]
Thanks, I gave it a try, and it seems to start up okay.  I'm still having some difficulties, but I'll open a separate ticket.
