### ISSUE TITLE
Error building hoogle and hindent

### ISSUE THREAD

**Issue by develop7** [rikvdkleij/intellij-haskell#281]
Repro:

1. Open Haskell project

Expected: no errors
Instead: 2 error popups with following text:

<details><summary>first</summary>

```
Executing `/home/develop7/bin/stack --stack-root /home/develop7/.intellij-haskell/lts-11 --resolver lts-11 --compiler ghc-8.2.2 --system-ghc --local-bin-path /home/develop7/.intellij-haskell/lts-11/bin install hoogle` failed: /home/develop7/bin/stack --stack-root /home/develop7/.intellij-haskell/lts-11 --resolver lts-11 --compiler ghc-8.2.2 --system-ghc --local-bin-path /home/develop7/.intellij-haskell/lts-11/bin install hoogle: Selected resolver: lts-11.13 Error: While constructing the build plan, the following exceptions were encountered: In the dependencies for hoogle-5.0.17.3: conduit-1.2.13 from stack configuration does not match >=1.3.0 (latest matching version is 1.3.0.2) needed since hoogle is a build target. Some different approaches to resolving this: * Set 'allow-newer: true' to ignore all version constraints and build anyway. * Consider trying 'stack solver', which uses the cabal-install solver to attempt to find some working build configuration. This can be convenient when dealing with many complicated constraint errors, but results may be unpredictable. * Recommended action: try adding the following to your extra-deps in /home/develop7/projects/stack/stack.yaml: - conduit-1.3.0.2 Plan construction failed.
```

</details><details><summary>Second</summary>

```
Executing `/home/develop7/bin/stack --stack-root /home/develop7/.intellij-haskell/lts-11 --resolver lts-11 --compiler ghc-8.2.2 --system-ghc --local-bin-path /home/develop7/.intellij-haskell/lts-11/bin install hindent` failed: /home/develop7/bin/stack --stack-root /home/develop7/.intellij-haskell/lts-11 --resolver lts-11 --compiler ghc-8.2.2 --system-ghc --local-bin-path /home/develop7/.intellij-haskell/lts-11/bin install hindent: Selected resolver: lts-11.13 hindent-5.2.5: configure hindent-5.2.5: build -- While building custom Setup.hs for package hindent-5.2.5 using: /home/develop7/.intellij-haskell/lts-11/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.0.1.0 build --ghc-options " -ddump-hi -ddump-to-file" Process exited with code: ExitFailure 1 Logs have been written to: /home/develop7/projects/stack/.stack-work/logs/hindent-5.2.5.log Configuring hindent-5.2.5... Preprocessing library for hindent-5.2.5.. Building library for hindent-5.2.5.. [1 of 4] Compiling HIndent.CabalFile ( src/HIndent/CabalFile.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.0.1.0/build/HIndent/CabalFile.o ) /tmp/stack25945/hindent-5.2.5/src/HIndent/CabalFile.hs:11:1: error: Could not find module ‘Distribution.PackageDescription.Parse’ Perhaps you meant Distribution.PackageDescription.Parsec (from Cabal-2.2.0.1) Distribution.PackageDescription.Check (from Cabal-2.2.0.1) Distribution.PackageDescription.Quirks (from Cabal-2.2.0.1) Use -v to see a list of the files searched for. | 11 | import Distribution.PackageDescription.Parse | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

</details>

Note: running above commands in a terminal succeeds.

**Comment by rikvdkleij** [comment]
Hmm, I just tested beta16 on Fedora and that part worked (I had a with problem with permissions on `.ghci` file and that is fixed in master).

This not a plugin issue:
```
error: Could not find module ‘Distribution.PackageDescription.Parse’ Perhaps you meant Distribution.PackageDescription.Parsec 
```

Why it succeeds in the terminal? I have no idea 😄

**Comment by rikvdkleij** [comment]
Maybe a `stack update` could have been the solution. But I do not want to this command every time a project is opened because it takes some time.

**Comment by rikvdkleij** [comment]
On a second thought, maybe the plugin should only install the Haskell tool binaries when they do not (yet) exist. When they are installed, the user should update the binaries by a menu option. Before the binaries are updated, `stack update` will be run.

**Comment by rikvdkleij** [comment]
Should be fix in next beta (if it is reproducible).

Thanks for your report! Made installing Haskell tools more user friendly.

**Comment by develop7** [comment]
Ya, running `stack update` in intellij-haskell's sandbox actually did update indexes.

**Comment by rikvdkleij** [comment]
@develop7 Should be fixed in beta17

**Comment by develop7** [comment]
@rikvdkleij no, the issue is still there. Funnily enough, running `stack --stack-root /home/develop7/.intellij-haskell/lts-11 --resolver lts-11 --compiler ghc-8.2.2 --system-ghc --local-bin-path /home/develop7/.intellij-haskell/lts-11/bin install hlint stylish-haskell hindent` still does build tools

**Comment by rikvdkleij** [comment]
Also when you use the menu option to update the Haskell tools?

**Comment by rikvdkleij** [comment]
I wonder if it’s an incident or a real issue (on Linux) The error messages are Stack build problems. They have nothing to do with the plugin itself.

Can you reproduce the problem by removing the LTS-11 directory and then opening the project in IntelliJ?

**Comment by develop7** [comment]
> Also when you use the menu option to update the Haskell tools?

Yes.

> Can you reproduce the problem by removing the LTS-11 directory and then opening the project in IntelliJ?

yup, that's exactly how I've been reproducing it.

**Comment by develop7** [comment]
Also soon after this I'm getting following exception: <details>

```
Cannot run program "/home/develop7/.intellij-haskell/lts-11/bin/hlint" (in directory "/home/develop7/projects/stack"): error=2, No such file or directory
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "/home/develop7/.intellij-haskell/lts-11/bin/hlint" (in directory "/home/develop7/projects/stack"): error=2, No such file or directory
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:395)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:51)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:44)
	at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:35)
	at intellij.haskell.external.execution.CommandLine$.createProcessHandler(CommandLine.scala:78)
	at intellij.haskell.external.execution.CommandLine$.run(CommandLine.scala:42)
	at intellij.haskell.external.component.HLintComponent$.runHLint(HLintComponent.scala:61)
	at intellij.haskell.external.component.HLintComponent$.check(HLintComponent.scala:39)
	at intellij.haskell.inspection.HLintInspectionTool$$anon$1.call(HLintInspectionTool.scala:51)
	at intellij.haskell.inspection.HLintInspectionTool$$anon$1.call(HLintInspectionTool.scala:48)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:328)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "/home/develop7/.intellij-haskell/lts-11/bin/hlint" (in directory "/home/develop7/projects/stack"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:423)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:391)
	... 14 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 16 more
```
</details>

**Comment by rikvdkleij** [comment]
> Also soon after this I'm getting following exception:

That is because after the build the plugin expects that hlint is installed.


> Funnily enough, running stack --stack-root /home/develop7/.intellij-haskell/lts-11 --resolver lts-11 --compiler ghc-8.2.2 --system-ghc --local-bin-path /home/develop7/.intellij-haskell/lts-11/bin install hlint stylish-haskell hindent still does build tools

Hmm, maybe it is working directory. What happens if you run that command in the root directory of a Stack project?

**Comment by rikvdkleij** [comment]
Fixed in beta18.

**Comment by rikvdkleij** [comment]
Hopefully the build problem is also fixed but I can not reproduce this issue on Mac and Fedora. I have changed the working directory in which the tools are build and hopefully that helps.

**Comment by develop7** [comment]
Confirming, the issue has been fixed.

**Comment by rikvdkleij** [comment]
Thanks for the confirmation!
