### ISSUE TITLE
Busy with installing hlint (again)

### ISSUE THREAD

**Issue by normenmueller** [rikvdkleij/intellij-haskell#350]
I'm using 1.0.0-beta36.

Each time I open (an already imported project), one process keeps running for quite some time:

> Busy with installing hlint in ${HOME}/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-12/bin

Is this necessary? @rikvdkleij Any explanation on what is going on there?

**Comment by rikvdkleij** [comment]
No, it should not happen after it is installed. Except when `Update Haskell Tools` is called.

I have never experienced this issue. Also why hlint and not other Haskell tools like hindent?

Can you check if the HlLint binary is really successfully installed in that bin directory?

**Comment by normenmueller** [comment]
@rikvdkleij subsequently the content of the cache:

```
[~]
$ cd Library/Caches/com.github.rikvdkleij.intellij-haskell/
[~/Library/Caches/com.github.rikvdkleij.intellij-haskell]
$ ls
GitHub Cli/ lib/        lts-12/     repl.ghci   scratch/    stack/

[~/Library/Caches/com.github.rikvdkleij.intellij-haskell]
$ cd lts-12/bin/

[~/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-12/bin]
$ ls
hindent*         hlint*           hoogle*          stylish-haskell*
[~/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-12/bin]
$
```

But still, every time I open a project, those get re-installed which lasts quite some time.

**Comment by rikvdkleij** [comment]
Yes, that is annoying but I have no explanation. Also because it works for the other Haskell tool binaries.

**Comment by rikvdkleij** [comment]
Btw, do you literally see
` ${HOME}`
or did you replace the original path?

**Comment by normenmueller** [comment]
As an example, you could try to import the [Stack](https://github.com/commercialhaskell/stack) project into IntelliJ-Haskell. I cloned the repos and then ran `stack setup && stack build` which worked just fine. But the import into IntelliJ failed... besides other issues one process is running forever (intallting Hlint).

If you have any clue how I could help (e.g., logs), just let me know.

**Comment by normenmueller** [comment]
> Btw, do you literally see
> ` ${HOME}`
> or did you replace the original path?

In [the post](https://github.com/rikvdkleij/intellij-haskell/issues/350#issue-388559369) I replaced the original path.

**Comment by rikvdkleij** [comment]
Which stack version are you using? On the IntellliJ Haskell gitter channel @develop7 mentioned that updating stack helped to import the Stack project successfully.

**Comment by normenmueller** [comment]
```
$ stack --version
Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) x86_64 hpack-0.31.1
```

**Comment by normenmueller** [comment]
Removed all "stuff" (`.idea/`, `.stack-work/`, ...) and successfully retried.

**Comment by rikvdkleij** [comment]
Great that it works now!

**Comment by normenmueller** [comment]
@rikvdkleij please let me reopen this issue, cause opening a project causes 

>Busy with installing hlint in ${HOME}/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-12/bin

to run for "ages". However, if I remove the project from "Welcome to IntelliJ IDEA" screen and re-import it, this runs very fast. 

There must be some issue here. BTW, the project I'm "playing" with is an empty project created via `stack new scratch simple`.

**Comment by normenmueller** [comment]
OK. I executed the following:

    $ rm -rf ~/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-12/
    
    $ stack --system-ghc -j1 --stack-root ~/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-12 --resolver lts-12 --compiler ghc-8.4.4 --local-bin-path ~/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-12/bin install hlint
    Selected resolver: lts-12.23
    Downloaded lts-12.23 build plan.
    Preparing to install GHC to an isolated location.
    This will not interfere with any system-level installation.
    Downloaded ghc-8.4.4.
    Installed GHC.
    Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/
    Downloading root
    Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/
    Downloading timestamp
    Downloading snapshot
    Downloading mirrors
    Cannot update index (no local copy)
    Downloading index
    Updated package index downloaded
    Update complete
    Populated index cache.
    [1 of 2] Compiling Main             ( /Users/nrm/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-12/setup-exe-src/setup-mPHDZzAJ.hs, /Users/nrm/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-12/setup-exe-src/setup-mPHDZzAJ.o )
    [2 of 2] Compiling StackSetupShim   ( /Users/nrm/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-12/setup-exe-src/setup-shim-mPHDZzAJ.hs, /Users/nrm/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-12/setup-exe-src/setup-shim-mPHDZzAJ.o )
    Linking /Users/nrm/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-12/setup-exe-cache/x86_64-osx/tmp-Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.4 ...
    clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
    clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
    base-compat-0.10.5: download
    base-compat-0.10.5: configure
    base-compat-0.10.5: build
    base-compat-0.10.5: copy/register
    ...
    hlint-2.1.11: download
    hlint-2.1.11: configure
    hlint-2.1.11: build
    hlint-2.1.11: copy/register
    Completed 47 action(s).
    Copying from /Users/nrm/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-12/snapshots/x86_64-osx/lts-12.23/8.4.4/bin/hlint to /Users/nrm/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-12/bin/hlint
    
    Copied executables to /Users/nrm/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-12/bin:
    - hlint
    
    Warning: Installation path
             /Users/nrm/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-12/bin
             not found on the PATH environment variable.

However, I explicitly run my Scratch project with lts-12.14. So, do I rather have to executed the following command:

    $ stack --system-ghc -j1 --stack-root ~/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-12 --resolver lts-12-14 --compiler ghc-8.4.3 --local-bin-path ~/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-12/bin install hlint
                                                                                                                          ^^^                   ^^^
Anyway, I then _re-imported_ my Scratch project. HLint was not installed again, but only the other Haskell tools:

    [~/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-12]
    $ ls
    bin/                   global-project/        programs/
    build-plan/            indices/               setup-exe-cache/
    build-plan-cache/      loaded-snapshot-cache/ setup-exe-src/
    config.yaml            precompiled/           snapshots/
    [~/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-12]
    $ ls bin/
    hindent*         hlint*           hoogle*          stylish-haskell*


Then I closed the Scratch project and _re-opened_ it. This time is it worked quite fast. Let's see and wait how it behaves. Therefore I'll leave the issue open.

**Comment by normenmueller** [comment]
Unfortunately it still does not work :-(

I closed the Scratch project and shutdown IntelliJ. Then I re-started IntelliJ and opened the Scratch project.... and, again, it keeps running "Busy with installing hlint...". I did not change anything, so I have no clue why this is happening. However, checking the content at `~/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-12` I can see that the `bin` directory is gone but I didn't remove it. So it makes sense that the Haskell Tools are re-installed but why is the `bin` directory gone? One thing I did before opening the project again is that I moved the project in a IntelliJ project group.

**Comment by rikvdkleij** [comment]
The `bin` directory is created when the Haskell tools are installed.

**Comment by rikvdkleij** [comment]
I have no idea why `bin` directory is gone. The plugin does not delete directories.

**Comment by rikvdkleij** [comment]
> One thing I did before opening the project again is that I moved the project in a IntelliJ project group.

Maybe you should reimport the project after this action.

**Comment by normenmueller** [comment]
> Maybe you should reimport the project after this action.

If I remove a project from IntelliJ and then reimport it, it not assigned to any group:

```
Group1
    Prj1
    Prj3
Group2
    Prj2
    Prj4
a(Re)ImportedPrj
```

**Comment by ice1000** [comment]
Same thing happens to me

**Comment by rikvdkleij** [comment]
A hanging stack build process is something else than a unexpected reinstall.

The plugin has no control over the build process.

**Comment by rikvdkleij** [comment]
Still, I never experienced any unexpected reinstall of Hlint or another Haskell tool. Do not know how to reproduce that.

**Comment by rikvdkleij** [comment]
@normenmueller 

> However, I explicitly run my Scratch project with lts-12.14. So, do I rather have to executed the following command:

That is a wrong idea, the Stack resolver of Haskell tools is independent of your Stack projects. Sorry, I did not mention that before.

**Comment by normenmueller** [comment]
@rikvdkleij On various blog post, though, I read that those Haskell tools like hlint should be installed with the same lts as the current project to function properly. 

Anyway, re the re-installation issue of hlint, I've the feeling that from time to time the entire `~/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-12/bin` dir is somehow removed. I'm investigating if this is related whether using IntelliJ groups or not.

**Comment by rikvdkleij** [comment]
@normenmueller 

> On various blog post, though, I read that those Haskell tools like hlint should be installed with the same lts as the current project to function properly.

That is not the case. Only `intero` has to be build with same GHC version as project (so not the Stack resolver version itself but it's GHC version).

See for more info/context:
https://github.com/ndmitchell/hlint/commit/7bb10df6871759704a287fedea623f5142ad2154

**Comment by rikvdkleij** [comment]
@ice1000 

> Same thing happens to me

Solved issue on Windows (did not check for `hlint.exe` but always `hlint`.

**Comment by ice1000** [comment]
@rikvdkleij I was going back to US the previous few days so I wasn't checking GitHub nofitications.
Will take a look at the bugfix and the quote handler stuff!

**Comment by rikvdkleij** [comment]
@ice1000 Thanks!

**Comment by ice1000** [comment]
Yes it's working. Bugfix confirmed

**Comment by normenmueller** [comment]
@rikvdkleij fyi, I just closed the current IntelliJ window returning to the project selection screen of IntelliJ. Then I just re-opened the just closed project and realized that `~/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-12/bin` was gone. So, again, `hlint` installation process started.

**Comment by rikvdkleij** [comment]
@normenmueller Thanks!

I assume hlint was still working before you closed the window.

Is it now reproducible? So each time you close window the folder is gone?

Still I have no idea what could be the cause...

**Comment by normenmueller** [comment]
@rikvdkleij 

> I assume hlint was still working before you closed the window.

No. Actually IntelliJ was ideal for quite some time.

> Is it now reproducible? So each time you close window the folder is gone?

Can't confirm yet but will keep you posted.

**Comment by normenmueller** [comment]
@rikvdkleij It's getting more and more bizarre. After closing IntelliJ completely, I wanted to check the `${HOME}/Library/Caches/com.github.rikvdkleij.intellij-haskell` directory... the entire directory was gone. Weird...

**Comment by normenmueller** [comment]
[CleanMyMac](https://macpaw.com/cleanmymac) is the criminal! Puh!

**Comment by rikvdkleij** [comment]
Great to hear that this mystery is solved :smile:

**Comment by i-schuetz** [comment]
Also getting this. I removed the .idea files, re-imported and removed `/Users/me/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-13/`, cleaned cache etc. Still hangs on "Busy with installing hlint". There's also the warning that Hoogle db doesn't exist, but I assume it's not related. 

Idea version: 
```
IntelliJ IDEA 2019.3.1 (Community Edition)
Build #IC-193.5662.53, built on December 18, 2019
Runtime version: 11.0.5+10-b520.17 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: Dart, GrepConsole, IdeaVIM, cz.malevic.plugins.characterposition, in.1ton.idea.spring.assistant.plugin, intellij.haskell, org.toml.lang, org.rust.lang, training
```

Plugin version:
```
1.0.0-beta52
```

OS:
```
MacOS 10.14.6 
```

**Comment by rikvdkleij** [comment]
@i-schuetz It can take some time before all Haskell tools are installed. Otherwise try beta56.

**Comment by i-schuetz** [comment]
I tried again and waited for about half an hour. Then I installed beta56 restarted and it's again stuck half an hour on "Busy with installing htlint in /....lts-14/bin".

**Comment by rikvdkleij** [comment]
@i-schuetz Don't know what is going on. Try to install `hlint` manually with one core, stack option `-j1`

**Comment by i-schuetz** [comment]
Okay I minimized IntelliJ and reopened a few hours later. It seems it finished. It's working.
