### ISSUE TITLE
IDE freeze

### ISSUE THREAD

**Issue by develop7** [rikvdkleij/intellij-haskell#512]
Repost of https://youtrack.jetbrains.com/issue/IDEA-233208

**Comment by rikvdkleij** [comment]
@develop7 I don't see attached thread dumps.

**Comment by develop7** [comment]
@rikvdkleij my bad. Just made them visible to "Rik van der Kleij" too

**Comment by rikvdkleij** [comment]
@develop7 I just released beta59, hopefully it solves this issue.

**Comment by develop7** [comment]
@rikvdkleij beta59 is affected as well 

here's fresh [threadDump-20200219-142847.txt](https://github.com/rikvdkleij/intellij-haskell/files/4224808/threadDump-20200219-142847.txt)

**Comment by rikvdkleij** [comment]
@develop7 Hmm, that's a pity :disappointed: 

How can I reproduce this issue?

**Comment by rikvdkleij** [comment]
@develop7 The thread dump does not contain useful info about that a plugin thread is as blocked.

**Comment by rikvdkleij** [comment]
@develop7 I can reproduce some lag with reproduce instructions from your Jetbrains issue. 

Does it help if you disable HLint inspection?

**Comment by develop7** [comment]
@rikvdkleij would a CPU profile help: [IU-193.6494.35_adziahel_20.02.2020_19.07.36.zip](https://github.com/rikvdkleij/intellij-haskell/files/4231763/IU-193.6494.35_adziahel_20.02.2020_19.07.36.zip)

**Comment by develop7** [comment]
> How can I reproduce this issue?

I couldn't reproduce it in a fresh project, hence not sure.

**Comment by rikvdkleij** [comment]
Thanks for your reply.

Eventually I could a bug which seems to be the cause. It should be fixed in beta61.

**Comment by rikvdkleij** [comment]
More performance improvements in beta62

**Comment by develop7** [comment]
@rikvdkleij the issue is still there, here's fresh CPU profile — 
[IU-193.6494.35_adziahel_26.02.2020_15.10.30.zip](https://github.com/rikvdkleij/intellij-haskell/files/4255664/IU-193.6494.35_adziahel_26.02.2020_15.10.30.zip)

hope that helps

**Comment by rikvdkleij** [comment]
Hmm, I didn't expect that :disappointed: 

How can I reproduce your issue? (if there is a consistent way in reproducing)

**Comment by rikvdkleij** [comment]
Ok, your profile is very useful. It goes wrong on an unexpected location....

**Comment by rikvdkleij** [comment]
Released beta63 :smile:

**Comment by develop7** [comment]
Yep, that fixes it! Thanks!

**Comment by rikvdkleij** [comment]
@develop7  Great! Thanks for your help!
