### ISSUE TITLE
Create new Haskell Module - Error adding module to project: null

### ISSUE THREAD

**Issue by DavidAntliff** [rikvdkleij/intellij-haskell#551]
I'm using 1.0.0-beta69 with Intelli-J IDEA Community 2020.1.1. I have Stack 2.3.1 installed and operational.

When attempting to create a new project from the "Welcome to IntelliJ IDEA" dialog, after selecting the Haskell Stack SDK path and a destination for the new project, I am returned to a view of the dialog, but it is unresponsive to mouse clicks. It stays this way for about a minute, and then the "busy" mouse cursor appears for perhaps another minute, or so. Then this error appears:

![Capto_Capture 2020-05-08_16-29-48_](https://user-images.githubusercontent.com/11261038/81370401-28b7dd80-9149-11ea-892d-e8dfb2a0c751.png)

Clicking OK opens the Project window, but no files have been created except the `.idea` subdirectory. There's nothing in the Haskell Event Log (I've enabled Haskell logging).

There is an IDE Fatal Error blinking in the bottom right corner:

```
Access is allowed from write thread only.

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@419ede51
Current thread: Thread[ApplicationImpl pooled thread 147,4,Idea Thread Group] 837968608
Write thread (volatile): Thread[AWT-EventQueue-0,6,Idea Thread Group] 1318827133com.intellij.openapi.diagnostic.Attachment@148b90e4
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsWriteThread(ApplicationImpl.java:1068)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsWriteThread(ApplicationImpl.java:1046)
	at com.intellij.openapi.application.impl.LaterInvocator.getCurrentModalityState(LaterInvocator.java:299)
	at com.intellij.openapi.application.impl.LaterInvocator.enterModal(LaterInvocator.java:156)
	at com.intellij.ui.messages.SheetMessage.<init>(SheetMessage.java:137)
	at com.intellij.ui.messages.JBMacMessages.showMessageDialog(JBMacMessages.java:73)
	at com.intellij.ui.messages.MessagesServiceImpl.showMessageDialog(MessagesServiceImpl.java:59)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:852)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:880)
	at intellij.haskell.module.HaskellModuleBuilder.$anonfun$createModule$1(HaskellModuleBuilder.scala:119)
	at intellij.haskell.util.ScalaUtil$.$anonfun$runnable$1(ScalaUtil.scala:35)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

If I close the Project window, then repeat the same process but choose the same directory as before, agreeing to overwriting the `.idea` directory, the project is created in a few seconds, and all the Stack templated files are present.

I tried the same thing again with a second new project, but this time repeating it a second (or third) time did not work. Up to this point I have not been able to create a new project since the first time it worked.

**Comment by rikvdkleij** [comment]
Currently the project importer is broken when importing a project from the Welcome Screen in IntellliJ 2020.1 because the IntelliJ SDK is changed.
As a workaround, the project importer is still working when using the option to import from existing sources in the File menu

**Comment by DavidAntliff** [comment]
@rikvdkleij thanks for your reply. With this issue, the problem occurs when _creating_ a new project, not when importing one. I was able to work around this by eventually getting a new project to be created (trial and error, it eventually worked, once), then copying it elsewhere and importing it as the new project (as you mention above). But the fundamental problem I'm reporting in this issue is with project creation, not importation.

**Comment by rikvdkleij** [comment]
Ok, I see.

Something goes wrong while creating a new project. The plugin wants to show the error message but then this error pop ups.
Will be fixed in next release.

Btw, for some reason the `stack new` command fails. That's the root cause.

**Comment by rikvdkleij** [comment]
Fixed in beta70

**Comment by DavidAntliff** [comment]
I gave beta70 a go - it does change something, the error "Error adding module to project: null" now comes up almost immediately, rather than after a minute or so, but there's still an error. Is there a way to somehow see the log to debug the "stack new" command? It creates the destination directory but nothing more.

If I manually run `stack new <project_name>` from the destination directory it runs to completion with no errors.

I'm wondering if it's caused by the Module name not matching the target directory? For example, I tend to use the `.git` suffix on directories that I keep under git, so I'm trying to create something like `path/to/my/project.git` for a project named "project". Yet it seemed to work for a shorter version of this so I'm not convinced yet.

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
