### ISSUE TITLE
Support `TypeApplications` Extension

### ISSUE THREAD

**Issue by vshatskyi** [rikvdkleij/intellij-haskell#76]
```Haskell
class ToValue a where
  toValue :: String

data Value = Value
instance ToValue Value where
  toValue = "value"

foo :: forall v. ToValue v => Proxy v -> String
foo _ = toValue @v -- parse error in expression: toValue@v
```

**Comment by rikvdkleij** [comment]
@vshatskyi When I try your example on master I do not get a parse error, I get error: `Not in scope: type variable 'v'`. So it seems it is already fixed on master.

Btw,
I have to enable also RankNTypes and have to import Data.Data.Proxy

**Comment by vshatskyi** [comment]
You need to enable `ScopedTypeVariables` to have `v` in scope. Here's the full list of extensions I have enabled, I'm not sure which ones are relevant.

```
  default-extensions:  MultiParamTypeClasses
                     , GADTs
                     , RankNTypes
                     , FlexibleInstances
                     , DataKinds
                     , PolyKinds
                     , TypeOperators
                     , TypeFamilies
                     , TypeInType
                     , ConstraintKinds
                     , ScopedTypeVariables
                     , AllowAmbiguousTypes
                     , TypeApplications
```

**Comment by rikvdkleij** [comment]
Thanks! No GHC error anymore with those extensions. I also do not get parse error from plugin. So it is already solved in master.

**Comment by vshatskyi** [comment]
Thank you.

**Comment by vshatskyi** [comment]
Just built it from master, still fails. Can you try to add this line at the end `type Foo = Int`?

**Comment by rikvdkleij** [comment]
Yes, that gives parse error. I will fix it.

**Comment by rikvdkleij** [comment]
O wait, this error is from HLint inspection  :smiley:

**Comment by vshatskyi** [comment]
My bad. Closing again.

**Comment by rikvdkleij** [comment]
Well, it's a pity that HLint does not send these kind of errors to stderr.

**Comment by rikvdkleij** [comment]
It is solved by building latest version of Hlint in project folder:
`stack build hlint-1.9.39 haskell-src-exts-1.19.0`

**Comment by rikvdkleij** [comment]
Or by putting resolver `nightly-2016-12-16` in project's stack.yaml.

**Comment by vshatskyi** [comment]
You're awesome, Rik, thank you.

**Comment by rikvdkleij** [comment]
Thanks :smiley:  I have put comment about this in README.
